### ISSUE TITLE
wrong formula in doc for Vector2D Reject

### ISSUE THREAD

**Issue by grondilu** [EricLengyel/Terathon-Math-Library#5]
I think the formula in the documentation is wrong.

It should not be (**a** - **a**.**b**)**b**, but rather **a** - (**a**.**b**)**b**

https://github.com/EricLengyel/Terathon-Math-Library/blob/ed1cbdf0b2603347720a13bdbcf19ad5561c97ab/TSVector2D.h#L124

The actual code seems fine, though:

https://github.com/EricLengyel/Terathon-Math-Library/blob/ed1cbdf0b2603347720a13bdbcf19ad5561c97ab/TSVector2D.h#L399

**Comment by EricLengyel** [comment]
Yes, that's a typo. Thanks for letting me know.
